juju-solutions/layer-apache-bigtop-base

layer.yaml

This is handled by layer-basic and was copy pasta'd.  I did a quick scan of the layers including this one, and did not find any referencing 'packages' as a bigtop-base layer option.  I'm like, 99% sure this is safe to remove.

remove 'packages' definition

---

resources/BIGTOP-2467.patch

The existing Bigtop puppet scripts write out the Zookeeper peers in such
a way that it is difficult to maintain a consistent id for each peer
across zoo.cfg files on different machines. This breaks Zookeeper,
because it expects peers to have a consistent id across machines.
This patch tweaks the puppet script so that it takes an explicit id in
addition to an ip address for each element that it writes out to the
config file, allowing the charm to majage the ids itself.
@juju-solutions/bigdata

Fixed zookeeper quorum bug: BIGTOP-2467

---

resources/BIGTOP-2478.patch

In combination with juju-solutions/layer-apache-bigtop-base/pull/22,
this adds Zookeeper smoke tests, and allows us to have a smoke-test
action in our Zookeeper charm.
@juju-solutions/bigdata

BIGTOP-2478 Added patch for Zookeeper smoke tests

---

actions.yaml
actions/smoke-test
layer.yaml
lib/charms/layer/apache_bigtop_base.py

This adds a smoke-test action to run the bigtop smoke tests when available.  The top layer charm should configure the bigtop_smoketest_components layer option to indicate which smoke tests should be run.
If a top layer charm does not have a bigtop smoke test, we should consider adding one to bigtop, or minimally include a smoke-test in that layer to override the one provided by this base layer.

Smoke tests

---

reactive/apache_bigtop_base.py

- lowercase status
- report accurate status after the base is installed (we're still in maintenance at this point, since bigtop base by itself cannot do anything)

status message updates

---

layer.yaml
lib/charms/layer/apache_bigtop_base.py

This gives us the ability to override hiera values in a more appropriate
place than site.yaml.
@juju-solutions/bigdata What do people think? Is this what we had in mind?
I've tested this with Zookeeper, and it seems to do the right thing.

Add a <charm>.yaml file to the hiera hierarchy

---

resources/bigtop-1.1.0/BIGTOP-1624.patch
resources/bigtop-1.1.0/BIGTOP-2504.patch

@juju-solutions/bigdata 
This is one of three pull requests for setting up the ability to bind kafka to an interface/ip address. I've run bundletester with the following permutations of 'bind_addr' in config.yaml:
1) Keeping the default value of null doesn't break anything, which is expected.
2) Passing in a value of 0.0.0.0 doesn't break anything, which is expected.
3) Passing in an address that doesn't match the address of the kafka server (e.g., 10.0.9.9) does break things.
My juju fu is not strong enough to setup a second interface on a machine and bind to that, but the above three tests do seem to indicate that the code does what I think that it does.
As part of this work, I also fixed up the kafka tests. It should be easy to get them to run, even if you aren't paying attention to …

Added a patch to allow kafka to bind to non default interface/ip

---

lib/charms/layer/apache_bigtop_base.py
resources/bigtop-1.1.0/BIGTOP-2506.patch
resources/pin-bigtop.txt

@juju-solutions/bigdata 
Puppet patch contains pass-through for clientPortAddress, so that we can
bind Zookeeper to listen on a specific interface.
As for the fixes ...
On Ubuntu Xenial, a Zookeeper package exists in universe, and we wind up
installing it rather than the one in Bigtop. This breaks many things.
In this change, we attempt to pin any given package to the Bigtop repo,
which fixes this, and should fix similar problems in the future.

Puppet patch, and fixes for Zookeeper on Xenial.

---

lib/charms/layer/apache_bigtop_base.py
tests/unit/test_bigtop.py

If someone passes 0.0.0.0 to get_ip_for_interface, the function will
return 0.0.0.0, which will then typically get written to a config,
allowing us to reset the software to listening on any interface.
@juju-solutions/bigdata

Added ability to reset interface bindings.

---

layer.yaml
lib/charms/layer/apache_bigtop_base.py
reactive/apache_bigtop_base.py
tests/unit/bigtop_harness.py
tests/unit/test_bigtop.py
tests/unit/test_reactive_handlers.py

This eliminates the need for the openjdk relation, which makes
Zookeeper more backwards compatible, and simplifies everything else.
@juju-solutions/bigdata

By default apache-bigtop-base installs Java.

---

layer.yaml
lib/charms/layer/apache_bigtop_base.py

This combines the 2 repo layer opts into 1 base repo url. We then construct
the appropriate url using the deployed series and machine architecture.
At least, that's how it's supposed to work. At the moment, it seems there
is no xenial repo, so for now, we hard code trusty and vivid as appropriate.
Fortuantely, the trusty repo works for installing bigtop packages on xenial.
So, this PR adds the scaffolding to support proper run time construction of the
repo url in the future.
While wiring this up, I noticed our hiera layer opts were poorly
named/described, so I fixed that. Speaking of options, I noticed we
were calling .options.get('opt') which does not fail like .options['opt']
when the option is missing. I made sure all required options used the []
syntax so we fail loudly if a required …

update bigtop repo handling (#43)

---

actions/smoke-test
layer.yaml
lib/charms/layer/apache_bigtop_base.py

We currently allow charms to specify a smoke_test_configs layer opt,
which is supposed to be files that we source prior to running the
smoke test. This is hard to handle because we don't know if that
file will be an ini, a dotfile, or some other thing that we have to
grok and source.
Seems smarter for the smoke test itself to construct a dict of all
the environment stuff it needs and pass that into the smoke test
runner.
This does that. I do not believe anyone is using the config file
madness, and it certainly didn't do anything in the smoke test
runner function, so I feel like now's the time to get on the right
path.

replace smoke test config files with env

---

lib/charms/layer/apache_bigtop_base.py
tests/unit/test_bigtop.py

Add helper to return a version string given a package name (currently, only dpkg is supported).  This is useful for `hookenv.application_version_set` when we only have the package manager to rely on.

add pkg version method (and unit tests)

---

layer.yaml
lib/charms/layer/apache_bigtop_base.py
tests/unit/test_bigtop.py

dphys-swapfile is special. On initial service start, it generates a file
to use as swap. This can take a long time, and on very slow/busy disks,
it will cause a systemd timeout (systemd gives services 60s to come up by
default).
We've seen cwr failures related to dphys-swapfile.service not starting,
which fails our runs. Let's do a few things:
- if the system already has swap, don't install dphys-swapfile
- if the package fails to install, inform the user (but since this isn't
a required package for bigtop, don't fail)
- if the service fails to start, inform the user why (again, since it's
optional, don't fail in this scenario either)

treat dphys-swapfile more especialer

---

layer.yaml
lib/charms/layer/apache_bigtop_base.py
tests/unit/test_bigtop.py

Setup our release bits (hieradata and puppet recipes) and package
repository based on the bigtop_version layer option.
Currently only '1.1.0' and 'master' are supported. For 1.1.0, we
still have to construct a funky repo url since the repo only supports
trusty (x86) and vivid (ppc). For master, we'll pull packages straight
from the ci system.
While we're here, let's simplify the layer options. Given the version,
we can construct everything else we need:
- remove bigtop_release_url
We don't need the user to set a release tarball url since we can git
clone it based on the version branch. This will break in a restricted
env that cannot access github, but it would probably break anyway trying
to wget a blob from apache.org. The right way to handle restricted envs
is to use resources so we can …

support installing from bigtop-master

---

lib/charms/layer/apache_bigtop_base.py

On LXD, if we have a host OS with no swap configured, our charms will attempt to setup swap space inside the containers.  This is bad because the host OS will effectively have this space "swapped on", which will prevent us from being able to destroy these containers:
```
ERROR while removing instance "juju-cb95ef-2": error removing /var/snap/conjure-up/common/lxd/storage-pools/default/containers/juju-cb95ef-2: rm: cannot remove '/var/snap/conjure-up/common/lxd/storage-pools/default/containers/juju-cb95ef-2/rootfs/var/swap': Operation not permitted
```

do not configure swap in containers

---

Makefile
README.md
actions.yaml
actions/reinstall
config.yaml
layer.yaml
lib/charms/layer/apache_bigtop_base.py
reactive/apache_bigtop_base.py
resources/pin-bigtop.txt
tests/unit/test_bigtop.py
tests/unit/test_reactive_handlers.py
tox_unit.ini

Allow users to specify the bigtop version as a runtime config option, e.g.:
juju config spark bigtop_version='1.2.1'
On change, this layer will fetch new bigtop source and add a corresponding apt repository with a low priority. This allows individual charms to query for new package versions and inform the user of possible actions.
A `reinstall` action template is also included here.  This should be modified as needed for individual charms in case there are application-specific tasks to perform when changing package versions.
The upgrade workflow goes like this:
- configure a new bigtop_version
- this base layer will setup the new bigtop source/repo and set `bigtop.version.changed`
- charms should react to this new state by calling `Bigtop.check_bigtop_repo_package` with an appropriate …

support bigtop charm upgrades

---

.travis.yml
Makefile
copyright
requirements.txt
tox.ini
tox_unit.ini
unit_test_requirements.txt

- add apache2 copyright like all our bigtop layers
- update makefile to include proof as part of the lint target
We also need to remove charm reqs (wheelhouse.txt) from tox_unit.ini.  Building a charm processes wheelhouse.txt and put those reqs in a ./wheelhouse subdir.  Tox will fail to run on a built charm because wheelhouse.txt will not exit.  Put whatever we need for unit tests into unit_test_requirements.txt since that file will be in the built charm output.

unit test and copyright updates

---

lib/charms/layer/apache_bigtop_base.py
tests/unit/test_bigtop.py

Binary packages for bigtop trunk are only available in the arch-specific
builder repositories. The multiple arches seen here only include no-arch
pkgs for non-intel arches:
https://ci.bigtop.apache.org/job/Bigtop-trunk-repos/OS=ubuntu-16.04,label=docker-slave/ws/output/apt/dists/bigtop/contrib/
Revert the recent change that used the above repo for all arches. We need
arch-specific builder arches on non-intel. Update unit tests to cover this
change.

arch-specific repo required for trunk

---

lib/charms/layer/apache_bigtop_base.py
tests/unit/test_bigtop.py

Revert pieces of #66. For bigtop 1.1.0 and 1.2.0, the correct repos
are still using bigtop-repos.s3. See the relevant bigtop.list at our
source of truth:
https://www.apache.org/dist/bigtop/
Set default release/series to 16.04/xenial. These are installable on
non-LTS releases, and are required to match the current bigtop repo
layout.
Remove useless checks for dist_name == 'ubuntu' since we fail fast
if someone tries to deploy a charm on non-ubuntu.
Kafka and non-intel are no longer available in the official repos
after 1.2. Ensure those cases are handled by setting the repo to the
correct CI repository.
Update the unit tests to deal with the above.

bigtop repo url fixes

---

Makefile
config.yaml

Switch the `install-cuda` default to True. If capable hardware is present,
CUDA should be automatically installed. Without this, users that deploy
to gpu instances have to explicitly configure `install-cuda=True`.
Setting this to True is a no-op on non-gpu hardware as layer-nvidia-cuda
will not do anything unless `lspci` detects an available gpu.
If an operator really wants GPU hardware without CUDA, they can always
configure with `install-cuda=False`.
... also get rid of pesky .pyc in our Makefile 'clean' target.

Install nvidia cuda on capable hardware

---

lib/charms/layer/apache_bigtop_base.py
tests/unit/test_bigtop.py

Looks like the workspace for repo jobs gets reaped, which means kafka and non-intel deployments may fail if a recent workspace isn't available.  Adjust repos to `lastSuccessfulBuild/artifact/` for these scenarios:
https://ci.bigtop.apache.org/job/Bigtop-1.2.1/OS=ubuntu-16.04/lastSuccessfulBuild/artifact/output/apt/

set a more stable repo for 1.2.1/kafka

---

README.md
actions/reinstall
actions/smoke-test
lib/charms/layer/apache_bigtop_base.py
reactive/apache_bigtop_base.py
tests/unit/test_bigtop.py
tests/unit/test_reactive_handlers.py

Recent updates to layer-basic include new conventions for dealing with layers.  First, now that layer-basic pulls in layer-options, let's do like the README says:
https://github.com/juju-solutions/layer-options
```
foo_opts = layer.options.get('foo')  # returns a dict of all the options
my_opt_1 = layer.options.get('foo', 'my_opt_1')  # returns just that option
```
Next, the [layer lib import convention](https://github.com/juju-solutions/layer-basic/pull/112) is to use `from charms import layer` followed by `layer.foo` to make the namespace of functions stand out a bit better. The old style still works, but we may as well future-proof before some little data spills out.

use current conventions from layer-basic
